CREATE TABLE "universe" (
	"token_address" text PRIMARY KEY NOT NULL,
	"symbol" text NOT NULL,
	"name" text NOT NULL,
	"decimals" integer NOT NULL,
	"onchain_uid" text NOT NULL,
	"authentic" boolean NOT NULL,
	"registry_source" text NOT NULL,
	"registry_checked_at" timestamp with time zone NOT NULL,
	"asset_status" text NOT NULL,
	"chainlink_feed" text,
	"feed_decimals" integer,
	"heartbeat_sec" integer,
	"max_staleness_sec" integer,
	"feed_age_sec" integer,
	"quote_bid" numeric(38, 18),
	"quote_ask" numeric(38, 18),
	"feed_agrees_with_quote" boolean DEFAULT false NOT NULL,
	"ui_multiplier" text NOT NULL,
	"new_ui_multiplier" text NOT NULL,
	"multiplier_effective_at" bigint,
	"registry_multiplier" text NOT NULL,
	"multiplier_mismatch" boolean DEFAULT false NOT NULL,
	"last_answer" text,
	"last_updated_at" bigint,
	"oracle_paused" boolean DEFAULT false NOT NULL,
	"token_paused" boolean DEFAULT false NOT NULL,
	"paused" boolean DEFAULT false NOT NULL,
	"is_trading_halt" boolean DEFAULT false NOT NULL,
	"price_usd" numeric(38, 18),
	"price_source" text,
	"liquidity_usd" numeric(38, 18) DEFAULT 0 NOT NULL,
	"pool_depth_usd" numeric(38, 18) DEFAULT 0 NOT NULL,
	"venues" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"redeemable" boolean DEFAULT false NOT NULL,
	"max_redeem_usd" numeric(38, 18) DEFAULT 0 NOT NULL,
	"sector" text,
	"factors" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"jurisdiction_blocks" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"signal_eligible" boolean DEFAULT false NOT NULL,
	"vault_eligible" boolean DEFAULT false NOT NULL,
	"ineligible_reasons" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"change24h_pct" numeric(18, 6),
	"spark_series" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"refreshed_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE INDEX "universe_symbol_idx" ON "universe" USING btree ("symbol");--> statement-breakpoint
CREATE INDEX "universe_signal_eligible_idx" ON "universe" USING btree ("signal_eligible");--> statement-breakpoint
CREATE INDEX "universe_vault_eligible_idx" ON "universe" USING btree ("vault_eligible");--> statement-breakpoint
CREATE INDEX "universe_refreshed_at_idx" ON "universe" USING btree ("refreshed_at");